### ISSUE TITLE
How can I use just the autoprefixer without optimus?

### ISSUE THREAD

**Issue by taha-k** [magnars/optimus-autoprefixer#1]
I am using deraen/lein-sass4clj "0.3.0" to compile my Sass files. 
  :sass {:source-paths ["src/sass"]
         :target-path "target/dev/resources/public/css"
         :source-map true
         :output-style :compressed}
Is there a way I can configure autoprefixer into this build?

**Comment by magnars** [comment]
You could add a build step that calls some code you write which would load the generated css, pipe it through autoprefixer, and then export it again.

**Comment by taha-k** [comment]
I am actually new with clojure and still figuring out stuff. I want to avoid using Gulp or some other build process. This is the only library I could find for autoprefixer with lein, if it is possible can you please write me a sample code? Thank you

**Comment by magnars** [comment]
Optimus was written to avoid Gulp and such build-step shenanigans. I'm hesitant to spend any time making up build-step Optimus-code. If you want example code, you could try using https://github.com/DomKM/optimus-sass and embrace Optimus instead.
